ISISComputingGroup/system_tests

Jenkinsfile

add environment to run

---

Jenkinsfile

Add journal parser tests.
https://github.com/ISISComputingGroup/IBEX/issues/2723
For acceptance criteria see main PR at https://github.com/ISISComputingGroup/JournalParser/pull/1
n/a
n/a
n/a
---

Add journal parser tests to jenkinsfile

---

test_genie_python_using_simple.py

Retries failing system tests. 
This is needed because blockserver PVs come up briefly, go down, and then come up for good, so a simple wait does not work. I've discussed the approach of retrying tests with @John-Holt-Tessella and we have agreed that while it's not particularly nice, it is significantly easier than other solutions in this case.
https://github.com/ISISComputingGroup/IBEX/issues/2848
- System tests run reliably
Not applicable
The system tests have been wrapped in a retry decorator, see above.
Not applicable
---

Retry tests on failure

---

test_genie_python_dae.py

Adds a test for DAE simulation mode python command
https://github.com/ISISComputingGroup/IBEX/issues/2927
Tests pass
Not applicable
System tests added for DAE simulation mode command
None
---

Add tests for DAE set sim mode

---

test_genie_python_dae.py

Try to get system tests to complete.

Setup dae before running

---

test_genie_python_dae.py

Add test on sample parameters in file saved by dae
See ISISComputingGroup/IBEX#4279
Tests pass
Added new test_GIVEN_running_instrument_WHEN_pars_changed_THEN_pars_saved_in_file test
---

Add DAE saved file system test

---

configs/rcptt_simple/blocks.xml

Added a block to the config needed for a new system test.
/
Tests in suite `test_genie_python_using_simple.TestWaitforBlock` pass.
/
/
/
---

Add block to fix failing system test

---

run_tests.py
test_genie_python_using_simple.py
test_plotting.py
utilities/utilities.py

Added unit tests for the ticket, and added retry on failure to all of the plotting tests, as some of them have been observed to occasionally fail on Jenkins.
https://github.com/ISISComputingGroup/IBEX/issues/4308
---

Ticket4308 limited number of plots

---

.gitmodules
Jenkinsfile7

Install ibex and also add temporary EPICS7 Jenkinsfile. Currently run as FreddieSystemTests jenkins job. You should remove the "branch = Ticket4604_local_ibex" line in gitignore prior to merge (or ask me to push a new version)
Merge ISISComputingGroup/ibex_utils#41 prior to merging this
See ISISComputingGroup/IBEX#4604
FreddieSystemTests jenkins job runs OK and has installed EPICS7 build
---

Add build files

---

run_tests.py
utilities/utilities.py

Fix tests, copy config to corret directory

---

Jenkinsfile

Add timestamps to jenkins output (as already done in epics builds)
---

Add timestamps

---

run_tests.bat

Use unbuffered output (makes Jenkins added timestamps better)
---

Set PYTHONUNBUFFERED

---

test_genie_python_dae.py

Tests added and merged too early see https://github.com/ISISComputingGroup/IBEX/issues/4828

Add skipper test back in after isisicp works

---

Jenkinsfile

Enable running of debug system test bui8lds
* merge changes
* enable System_Tests_debug jenkins project
* check it installs debug build
---

Enable running of debug build tests

---

run_tests.bat
run_tests.py
utilities/utilities.py

System tests need to run in python3 to use the latest version of python 3
https://github.com/ISISComputingGroup/IBEX/issues/5376
System tests run
---

Make system tests run in python3

---

run_tests.bat
test_genie_python_common_imports.py
test_genie_python_dae.py

Fix tests after going to python3

Fix remaining failing tests

---

test_genie_python_dae.py

Fix string comparison by decoding bytes -> unicode
* system tests pass
---

Fix run title byte/unicode string comparison

---

test_genie_python_dae.py

convert hdf5 byte string to unicode
test passes
---

Missed another string comparison

---

configs/configurations/rcptt_simple/blocks.xml
test_genie_python_dae.py

Add basic test for alarm logging array
See ISISComputingGroup/IBEX#4936
* test passes
---

Basic test for alarm logging array

---

test_genie_python_dae.py

Re-enable tests
See ISISComputingGroup/IBEX#4828
* tests run successfully
---

Re-enable tests

---

test_genie_python_dae.py
test_genie_python_using_simple.py

Fix tests after genie_python api changes

Fix test+after genie changes

---

test_genie_python_dae.py

Add sleep between file read retries
* system tests pass that read nexus file
---

Add sleep between file read retries

---

run_tests.bat

Check error code returned by system tests
See ISISComputingGroup/IBEX#5479
* failed tests now fail build
---

Check exit codes

---

test_datastreaming.py

Fixes datastreaming tests on machines that do not have docker
Run the datastreaming tests on a machine without docker running and confirm it skips
---

Added check for docker on tear down

---

test_genie_python_dae.py

Correct string - should be a raw string
---

Use raw string

---

test_genie_python_using_simple.py

Add system test for alerts
See ISISComputingGroup/IBEX#5491
* tests pass
---

Initial alert system tests

---

test_genie_python_using_simple.py

Fixes test I broke in https://github.com/ISISComputingGroup/genie_python/pull/273/commits/89d43915c154f0397a6af0e948d74485b2b68d65
---

Fixed broken test

---

test_genie_python_using_simple.py

Fix final assert

---

utilities/utilities.py

Increased server timeout so for config switch

increased server timeout

---

utilities/utilities.py

fixed typo

---

test_start_stop_ioc_through_proc_control.py
utilities/utilities.py

https://github.com/ISISComputingGroup/IBEX/issues/5568
---

Add test for starting and stopping all iocs

---

test_start_stop_ioc_through_proc_control.py
utilities/utilities.py

System tests were failing on a timeout, increase this for the time being. Also IOC does not start so create an exception for it.
---

Increase timeout, add to exceptions of iocs

---

test_genie_python_using_simple.py

System test for the DISP warning functionality that has been added to genie_python 
ISISComputingGroup/IBEX#5674
See ticket
None added
Added some system tests to check that genie_python warns a user if DISP is set on a PV
Will add something to the wiki to explain new warning
---

Ticket5674: DISP warning

---

test_blockserver.py

https://github.com/ISISComputingGroup/IBEX/issues/5803
https://github.com/ISISComputingGroup/IBEX/issues/5803
https://github.com/ISISComputingGroup/IBEX/issues/5803
---

Add test for ticket 5803

---

test_start_stop_ioc_through_proc_control.py

Skip MK3Chopper
https://github.com/ISISComputingGroup/IBEX/issues/5856
https://github.com/ISISComputingGroup/IBEX/issues/5856
n/a
n/a
---

Skip MK3Chopper

---

Jenkinsfile

Cleanup EPICS install directory post test run
---

Remove EPICS install directory after tests run

---

test_genie_python_using_simple.py

Tests basically already existed, I just made them explicit. See https://github.com/ISISComputingGroup/IBEX/issues/5082.
* Confirm tests work
* Confirm they would have caught previous issue
---

Ticket 5082: Made it more explicit that test are also checking is_local

---

create_virtual_env.bat
run_tests.bat
test_genie_python_dae.py

For https://github.com/ISISComputingGroup/IBEX/issues/5786
Although this does not not actually reproduce the race in the original ticket on my machine or on DEMO, I still feel it is a useful test to add to catch similar future regressions.

Ticket5786 run control race condition

---

requirements.txt

Pinning compose version - possible bug with latest version causing --no-log-prefix issue

---

requirements.txt
test_datastreaming.py

unpinning docker compose version and using --no-log-prefix instead

---

configs/configurations/block_in_title/meta.xml
configs/configurations/empty_for_system_tests/meta.xml
configs/configurations/memory_usage/meta.xml
configs/configurations/rcptt_simple/meta.xml
configs/configurations/test_blockserver_with_gw_archiver/block_config.xml
configs/configurations/test_blockserver_with_gw_archiver/blocks.xml
configs/configurations/test_blockserver_with_gw_archiver/components.xml
configs/configurations/test_blockserver_with_gw_archiver/groups.xml
configs/configurations/test_blockserver_with_gw_archiver/gwblock.pvlist
configs/configurations/test_blockserver_with_gw_archiver/iocs.xml
configs/configurations/test_blockserver_with_gw_archiver/meta.xml
configs/configurations/test_blockserver_with_gw_archiver/rc_settings.cmd
configs/configurations/test_blockserver_without_gw_archiver/blocks.xml
configs/configurations/test_blockserver_without_gw_archiver/components.xml
configs/configurations/test_blockserver_without_gw_archiver/groups.xml
configs/configurations/test_blockserver_without_gw_archiver/iocs.xml
configs/configurations/test_blockserver_without_gw_archiver/meta.xml
test_blockserver.py
utilities/utilities.py

Test the ability to specify custom block_config.xml and gwblock.pvlist files in a configuration
https://github.com/ISISComputingGroup/IBEX/issues/5069
---

Test the ability to specify custom block_config.xml and gwblock.pvlist files in a configuration

---

Jenkinsfile
clean_files.bat

Clean DAE files generated during previous system tests
See ISISComputingGroup/IBEX#6165
* c:\data is cleaned up prior to job starting
---

Clean DAE files

---

test_memory_usage.py

Add test to check commit size of python processes are reasonable
https://github.com/ISISComputingGroup/IBEX/issues/6394
---

Add test to check commit size is reasonable

---

Jenkinsfile

See https://github.com/ISISComputingGroup/IBEX/issues/6555. Adds running the IOC system tests to the general system tests.
With the other changes on the linked ticket merged, merge this and confirm that when Jenkins runs it:
* The CCD100 IOC tests are run
* All other IOC tests are run
* The reports of all tests are correctly passed to jenkins
* The artifacts of the tests are correctly uploaded to jenkins
---

Ticket 6555: Added running IOC System tests to system tests

---

Jenkinsfile

Fix gathering test output,
combine tests stages to avoid race condition
make sure correct overall error status returned

Fix gathering test output

---

test_memory_usage.py

Remove nicos memory check as now optionally started

Remove nicos as now optionally started

---

test_start_stop_ioc_through_proc_control.py
utilities/utilities.py

Re-enabled test, refactored it to make it clearer and faster. Fixed failure
https://github.com/ISISComputingGroup/IBEX/issues/6769

Ticket6769 steps to re enable start stop iocs

---

configs/configurations/test_blockserver_save_active_config/blocks.xml
configs/configurations/test_blockserver_save_active_config/components.xml
configs/configurations/test_blockserver_save_active_config/groups.xml
configs/configurations/test_blockserver_save_active_config/iocs.xml
configs/configurations/test_blockserver_save_active_config/meta.xml
test_blockserver.py

Added a test to check saving to currently active configuration behaviour.
https://github.com/ISISComputingGroup/IBEX/issues/7224
See ticket.
---

Ticket7224

---

test_plotting.py

Fixes system_tests for new plotting code

Fix plotting tests for new plotting code

---

README.md

Added a line to include the fact that you have to clone this repo separately to the majority of the others. 
None
---

Add clearer dev instructions

---

test_instrument_scripts.py

Fix instrument scripts tests.

---

test_blockserver.py

add test for reapplying autorestart to special case IOCs

---

Jenkinsfile

re-enable early fail of tests

---

run_tests.py

Check success

---

run_tests.py

Load config before checking DAE is running

Load config before checking DAE is running

---

configs/configurations/bluesky_sys_test/blocks.xml
configs/configurations/bluesky_sys_test/components.xml
configs/configurations/bluesky_sys_test/groups.xml
configs/configurations/bluesky_sys_test/iocs.xml
configs/configurations/bluesky_sys_test/meta.xml
requirements.txt
test_bluesky.py

https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/15
---

Initial system tests

---

test_bluesky.py

System tests to match https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/45

Adjust system tests for adjusted logging setup, add more tests

---

test_genie_python_dae.py

Add change title spped test
See ISISComputingGroup/IBEX#8486
Test passes
---

Add change title speed test

---

requirements.txt

required by 
https://github.com/ISISComputingGroup/system_tests/blob/master/test_setup_teardown.py#L4

add configobj to requirements.txt

---

test_bluesky.py

bluesky consolidate imports - fix tests

---

test_genie_python_dae.py

Won't pass until https://github.com/ISISComputingGroup/genie/pull/53 and https://github.com/ISISComputingGroup/EPICS-isisdae/pull/98 is merged.
Just adds a couple tests to check that you can use the genie commands to read and write to this PV

Added tests for autosave freq
