test_genie_python_common_imports.py

Tests that all of genie_python's packages are importable (i.e. you can import them without it raising an error, and you get back a module).
https://github.com/ISISComputingGroup/IBEX/issues/2932
System test added as described above.
N/a
---

Test genie_python can import all packages it has.

---

test_plotting.py

Add smoke tests for plotting. 
It's pretty much impossible to test that the plots are actually displaying the right thing, but we can still check:
- That exceptions are not thrown
- That the matplotlib webserver is accessible once we've displayed a plot
https://github.com/ISISComputingGroup/IBEX/issues/3058
Primary functionality is at least tested to the point that it does not throw exceptions or hang
https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Matplotlib
---

Add basic smoke tests for matplotlib

---

test_genie_python_dae.py
utilities/utilities.py

Fix failing build by using genie python straight and setting the throw flag
This failed after API is no longer in genie it is in setup and was being referenced.

Set raises exception flag to make test easier

---

test_genie_python_using_simple.py

Adds system tests to ensure the keyword argument syntax for `g.cset` works properly.
https://github.com/ISISComputingGroup/IBEX/issues/4152
- See unit tests added in genie_python PR
- Yes
Not required for this change.
---

Add system tests for cset using keywords args

---

test_genie_python_using_simple.py

System tests to check `waitfor_pv` command works. Needed for zeroing motors for reflectometry via genie_python.
https://github.com/ISISComputingGroup/IBEX/issues/3895
-
-
-
---

Added system tests for waitfor_pv command

---

test_genie_python_using_simple.py
utilities/utilities.py

Unable to reproduce the bug. Added tests to confirm waitfor_blocks behaves as expected and to catch any future errors. 
Numeric block added for test on test machine by @ThomasLohnert 
https://github.com/ISISComputingGroup/IBEX/issues/4147
---

Ticket4147 waitfor blocks limits

---

README.md
run_tests.bat
run_tests.py

Added code so that you ca give command line arguments with the -t tag to the run_tests.py script so you can run test from individual modules, classes or even individual tests, or multiple individual tests that you name.
Now, you can run a subset of all tests just as you are able to do in the IOC Tests Framework.
https://github.com/ISISComputingGroup/IBEX/issues/5109
Developers can select indvidual system tests to run
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Running-Automated-System-Tests
---

Ticket5109 run individual tests

---

test_genie_python_dae.py
utilities/utilities.py

Added system tests to test the genie python commands for changing the period and the total number of periods for both normal and for invalid input. 
https://github.com/ISISComputingGroup/IBEX/issues/4992
Newly added system tests pass on dev machines and also on our build server.
2 for each of the two methods, one for normal input and for when genie python now throws an error. The tests for change_period are parameterized and use Boundary Value Analysis.
---

Ticket4992 raise invalid period exception

---

test_genie_python_dae.py

Two tests were failing since two paths were not equal because one directory was capitalized in one string, but not in the other. Windows paths are case insensitive, so it is irrelevant if it is capitalised or not.
The two system tests were consistently failing on builds before and including #987 .
The two system tests pass on dev machines and also on Jenkins after this is merged
---

made asserts case insensitive

---

.gitignore
run_tests.bat
test_memory_usage.py

Compares the memory usage difference from before IBEX began and after, rather than the whole usage of the system. This was causing issues on the build server where another process was using a large amount of memory.
* Run something on your machine that is not IBEX part of the IBEX server but uses >9 GB of memory
* Run `run_tests.bat -t test_memory_usage` on master, confirm it fails
* Run `run_tests.bat -t test_memory_usage` on this branch and confirm it passes
---

Memory Usage

---

test_memory_usage.py

Checks memory usage better so that tests can be run on any hardware.
Note: Once this is done we should reinstate these tests on NDHSPARE70
Run the memory system tests on a developer machine with some other large processes running in the background and confirm that they still work.
---

Actually check memory and assume os usage

---

test_genie_python_dae.py
utilities/utilities.py

* Adapted test to ignore additional samples
* Forced an invalid sample at the end of the test to make sure it works
* Added retry for the nexus file access
To test:
* Run the modified test a few times and confirm it works reliably
See https://github.com/ISISComputingGroup/IBEX/issues/5483
---

Ticket 5483: Fix DAE block test

---

test_genie_python_using_simple.py

Add system test for g.alerts.send()
See ISISComputingGroup/IBEX#5555
* running system test via `run_tests.bat -t test_genie_python_using_simple.TestAlerts` works
---

Add system test for g.alerts.send()

---

run_tests.py
test_genie_python_using_simple.py

Made the error message for when files can not be deleted by the run tests python script be printed. That is to see why the Windows 10 system tests failed.
I changed the assertions for  a test to fix the failure on the normal system test, because as a result of  https://github.com/ISISComputingGroup/EPICS-RunControl/pull/10 the delays have been changed to 0, but the assertions were not.
the system tests pass succesfully
---

Fix deletion retries

---

test_genie_python_dae.py

Block alarm statuses that have changed before a run has started can be logged into the nexus file in some cases. These values confuse the tests and so this ticket filters them out .
To test:
* Run the modified test and confirm it passes
---

Filter out values that have come in outside run

---

test_start_stop_ioc_through_proc_control.py

Don't try to start/stop certain IOCs which we know are problematic

Ignore non-runnable iocs

---

test_start_stop_ioc_through_proc_control.py
utilities/utilities.py

Restarts IOCs in RECSIM if they fail to start in DEVSIM. If they still fail to start, they are reported. 
ISISComputingGroup/IBEX#5861
See ticket
N/a
Tests now restart an ioc in recsim if they fall over the first time. 
None
---

Ticket5861: Retrying in recsim if IOC fails to start

---

run_tests.bat
run_tests.py
test_genie_python_dae.py
utilities/utilities.py

Added tests forget_time_since_start function in genie_dae.py. 
Created method to get execution time of a method.
https://github.com/ISISComputingGroup/IBEX/issues/6519
There are system_tests for this function
Tests for testing get_time_since start:
1. With/without pause
2. Returning seconds(False)/datetime object(True)
---

Ticket6519 add system tests for get time since start

---

test_genie_python_common_imports.py

Add black library to IGNORED_MODULES variable in test_genie_python_common_imports.py to fix system tests. black is not a required module, but is shipped with ipython library
HOTFIX to Add black to `IGNORED_MODULES` varaible in `system_tests\test_genie_python_common_imports.py` as the dependency is not required, but shipped alongside [Ipython](https://pypi.org/project/ipython/) to pass system tests for release 10.0.0
**see [Jenkins build](https://epics-jenkins.isis.rl.ac.uk/job/System_Tests_release/10/testReport/junit/test_genie_python_common_imports/TestGeniePythonImports/test_WHEN_importing_all_installed_packages_THEN_no_error/) for error being fixed by this PR**
- `system_tests\test_genie_python_common_imports.py`
---

HOTFIX - Fix Genie Python System Test

---

test_genie_python_dae.py

Added a new system test for the DAE and refactored a private method (`_wait_for_sample_pars`) to be more generic (`_wait_for_method`).
[Ticket7208](https://github.com/ISISComputingGroup/IBEX/issues/7208)
- Added `test_GIVEN_no_instetc_WHEN_get_rb_and_begin_run_THEN_dae_state_is_running`. 
Can be run with: 
`python run_tests.py -t test_genie_python_dae.TestDae.test_GIVEN_no_instetc_WHEN_get_rb_and_begin_run_THEN_dae_state_is_running`
---

Ticket 7208 - Add system test to confirm can begin without rb number / instetc

---

configs/configurations/test_restart_ioc_when_pv_in_alarm/blocks.xml
configs/configurations/test_restart_ioc_when_pv_in_alarm/components.xml
configs/configurations/test_restart_ioc_when_pv_in_alarm/groups.xml
configs/configurations/test_restart_ioc_when_pv_in_alarm/iocs.xml
configs/configurations/test_restart_ioc_when_pv_in_alarm/meta.xml
test_restart_ioc_when_pv_in_alarm.py

Added test for the `restart_ioc_when_pv_in_alarm` script.
https://github.com/ISISComputingGroup/IBEX/issues/7291
See ticket.
---

Ticket7291

---

test_genie_python_common_imports.py

In `test_genie_python_common_imports.py`, added an exception for importing private modules.
Link to ticket: https://github.com/ISISComputingGroup/IBEX/issues/7312
---

Add exception for importing private packages

---

Jenkinsfile

Rearrange install so:
previous: install to EPICS, rename this to EPICS-SystemTests, create junction from EPICS -> EPICS-SystemTests
now:  create empty EPICS-SystemTests, create junction from EPICS -> EPICS-SystemTests, install to EPICS
the new approach hopefully has less likelihood of leaving a part empty EPICS dir, we have removed the "rename" which was place most likely to fail due to a file in use

Rearrange install location order

---

utilities/utilities.py

Use newly exposed `pv_exists` command to reduce printing

use pv_exists to remove excess messages

---

configs/configurations/advanced/blocks.xml
configs/configurations/advanced/components.xml
configs/configurations/advanced/groups.xml
configs/configurations/advanced/iocs.xml
configs/configurations/advanced/meta.xml
test_genie_python_advanced.py

Added tests and configuration for new support of redefining motor positions from the genie command line. 
[Ticket8411](https://github.com/ISISComputingGroup/IBEX/issues/8411)
- All tests pass
- Tests are extensive enough
- test_GIVEN_manager_mode_WHEN_calling_get_manager_mode_THEN_returns_true - Test that setting when setting the manager mode to a new value, g.adv.get_manager_mode() returns this value.
- test_GIVEN_no_manager_mode_WHEN_setting_motor_position_THEN_exception_is_raised - Test that if the user is not in manager mode they cannot redefine motor position.
- test_GIVEN_invalid_motor_name_WHEN_setting_motor_position_THEN_exception_is_raised - Checks that if the motor name supplied is not valid then an exception is thrown.
- …

Ticket8411_motor_control_genie_cli_tests

---

Jenkinsfile
clear_logs.bat

This is to avoid issues where job terminates very early in e.g. ibex install or git checkout and ends up reporting previous unit test results

Clear logs more often to avoid erroneous reporting

---

README.md
test_bluesky.py

Some system tests have been added for testing the bluesky logger
[*Link to Ticket*](https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/23)
The system tests should run successfully as a complete set or when executed individually
Added tests to check the following: 
1. Log folder is created when logging is requested
2. Log file is created when logging is requested
3. The log message is present in the log file.

Ticket 23 configure bluesky logging

---

run_tests.bat

In sprint review 2024/11/27 there seemed to be a slight preference to run system tests explicitly against main branches.
This PR does that.

Explicitly run system tests against main branch of genie_python and ibex_bluesky_core

---

test_genie_python_using_simple.py

Updates `test_genie_python_using_simple` to use `get_instrument_full_name` as previously when constructing `path_to_inst` the machine name was returning "" and the path would be incorrect.

Fixes pyright system tests

---

run_tests.py

this way we'll actually get told about tests that error in our CI.

make genie python raise exceptions by default

---

requirements.txt
test_bluesky.py

add system test for standard callbacks

---

test_genie_python_using_simple.py

Pass is_local flag to second cget

---

test_memory_usage.py

Increase acceptable memory usage - test failed recently with
```
AssertionError: Expected commit size to be less than values: {'block_server.py': 900000, 'database_server.py': 900000}. Actually got: {'database_server.py': 910766.08, 'block_server.py': 918765.568}
```

Increase test memory allowance check

---

configs/configurations/memory_usage/iocs.xml
configs/configurations/memory_usage/meta.xml
test_memory_usage.py
utilities/utilities.py

Increase config load timeout for large memory test config
---

Increase timeout and update configs

---

test_genie_python_dae.py

Add test that a non-changing block is logged at least once under a variety of different run duration conditions
ISISComputingGroup/IBEX#8720
---

Archiver fast restart
